# Generated by Django 4.1.7 on 2023-03-15 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(db_index=True, default=False, verbose_name='Оплачена')),
                ('payment_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата оплаты')),
                ('menu_type', models.CharField(choices=[('CLASSIC', 'Классическое'), ('LOW_CARB', 'Низкоуглеводное'), ('VEGETARIAN', 'Вегетарианское'), ('KETO', 'Кето')], max_length=10, verbose_name='Тип меню')),
                ('period', models.CharField(choices=[('1', '1 месяц'), ('3', '3 месяца'), ('6', '6 месяцев'), ('12', '12 месяцев')], max_length=2, verbose_name='Срок подписки')),
                ('breakfast', models.BooleanField(verbose_name='Завтрак')),
                ('lunch', models.BooleanField(verbose_name='Обед')),
                ('dinner', models.BooleanField(verbose_name='Ужин')),
                ('dessert', models.BooleanField(verbose_name='Десерт')),
                ('person_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Количество персон')),
                ('allergy', models.CharField(choices=[('f', 'Рыба и морепродукты'), ('m', 'Мясо'), ('c', 'Зерновые'), ('b', 'Продукты пчеловодства'), ('n', 'Орехи и бобовые'), ('d', 'Молочные продукты')], max_length=6, verbose_name='Аллергии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
