# Generated by Django 4.1.7 on 2023-03-15 19:35

from django.db import migrations


def add_menu(apps, schema_editor):
    Menu = apps.get_model('food', 'Menu')

    menu_types = [
        {'name': 'Классическое'},
        {'name': 'Низкоуглеводное'},
        {'name': 'Вегетарианское'},
        {'name': 'Кето'}
    ]

    for menu_type in menu_types:
        Menu.objects.get_or_create(name=menu_type['name'])


def add_subscription(apps, schema_editor):
    Subscription = apps.get_model('food', 'Subscription')

    subscriptions = [
        {'period': '1', 'price': 100},
        {'period': '3', 'price': 300},
        {'period': '6', 'price': 600},
        {'period': '12', 'price': 1200},
    ]

    for subscription in subscriptions:
        Subscription.objects.get_or_create(
            period=subscription['period'],
            price=subscription['price']
        )


def add_category(apps, schema_editor):
    Category = apps.get_model('food', 'Category')

    categories = [
        {'name': 'Завтраки'},
        {'name': 'Обеды'},
        {'name': 'Ужины'},
        {'name': 'Дессерты'}
    ]

    for category in categories:
        Category.objects.get_or_create(name=category['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_menu),
        migrations.RunPython(add_subscription),
        migrations.RunPython(add_category),
    ]
