# Generated by Django 4.1.7 on 2023-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_recipe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
