# Generated by Django 4.1.7 on 2023-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preview_text',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
