# Generated by Django 4.1.7 on 2023-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_recipe_preview_text_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes', verbose_name='Изображение'),
        ),
    ]
